import type { Metadata, Viewport } from "next";
import { ThemeProvider } from "next-themes";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ServiceWorkerRegister } from "@/components/pwa/ServiceWorkerRegister";
import { I18nProvider } from "@/i18n/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "UndePescuim.ro",
  description: "Harta apelor de pescuit contractate din România — contracted fishing waters in Romania",
  manifest: "/manifest.webmanifest",
  // F6 (t_0618943a): PWA installability (offline-pwa-feasibility.md §5).
  // iOS has no beforeinstallprompt — users install via "Share → Add to Home
  // Screen"; these meta tags make the result a standalone, chrome-less app.
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "UndePescuim",
  },
  icons: {
    // apple-touch-icon: iOS home-screen icon (solid, 180px, generated by
    // scripts/gen-icons.mjs). No transparency — Apple fills it black otherwise.
    apple: [
      {
        url: "/icons/apple-touch-icon-180x180.png",
        sizes: "180x180",
        type: "image/png",
      },
    ],
  },
};

// Android/Chromium status-bar color (matches the manifest theme_color).
export const viewport: Viewport = {
  themeColor: "#171717",
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  colorScheme: "light dark",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="ro"
      // suppressHydrationWarning is REQUIRED with next-themes: it mutates
      // <html class> on the client before hydration (attribute="class"),
      // so the server-rendered class can legitimately differ.
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col overscroll-none">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* t_920a7b7b: i18n context — per-locale strings + the header
              switcher. RO is the SSR default; persisted/browser locale is
              applied client-side (no hydration mismatch). */}
          <I18nProvider>{children}</I18nProvider>
        </ThemeProvider>
        {/* F6 PWA light: register the Serwist SW (prod builds only — dev has
            no cache tier and a stray SW would confuse HMR). */}
        <ServiceWorkerRegister />
      </body>
    </html>
  );
}
