import { create } from 'zustand';
import type { Association, ContractFilter, CountyFeature, Water, WaterTypeFilter } from '@/types/data';
import { distanceToWaterKm, nearbyCounty, nearestWaters, type NearbyWater } from '@/utils/geo';

/** Geolocation MVP constants (docs/geolocation-feasibility.md §5). */
export const DEFAULT_RADIUS_KM = 25;
export const EXPANDED_RADIUS_KM = 50;
export const MIN_NEARBY_COUNT = 3;
export const NEARBY_LIMIT = 10;

/**
 * Single source of truth for all cross-component map UI state.
 * Contract: docs/component_structure_plan.md §5.1 + docs/map-state-data-flow.md §1.
 *
 * Rules:
 * - Selection and filters are INDEPENDENT (R10) — no action clears another's state.
 * - t_21d2f68d: filter changes NEVER clear the selected water (R9 removed).
 *   A locality/county/type/contract filter narrows the VISIBLE waters but the
 *   selection (orange focus + detail card) persists — the reported bug was a
 *   locality pick silently dismissing the clicked water the moment it fell
 *   outside the picked UAT ("all highlights disappear"). The selected water is
 *   pinned into the rendered set instead (use-filtered-waters) so the focus
 *   stays visible; clearing the filters restores the full view.
 *
 * t_471dad64: `waters` are the CONTRACTED waters (association cards);
 * `uncontracted` are the OSM rivers with NO contract (teal overlay,
 * 'Necontractat' cards). They stay separate so contract-resolution logic
 * (contractAtFraction over `waters`) never sees the uncontracted entries.
 */

interface MapStore {
  // Data layer (loaded once, never mutated after load)
  associations: Association[];
  waters: Water[];
  uncontracted: Water[];
  /** County boundary polygons (/data/counties.geojson) — nearby chip attribution (t_6c2ac870). */
  counties: CountyFeature[];
  /**
   * Data freshness (F6, docs/offline-pwa-feasibility.md §6): ISO timestamp of
   * the last commit touching public/data, from /data/meta.json (generated by
   * scripts/gen-meta.mjs during prebuild). null = meta not available (dev).
   */
  dataUpdatedAt: string | null;
  dataLoaded: boolean;
  /**
   * P0 §4.2 (plan §4.2/§4.2b): per-county render clips are split OUT of
   * waters.json into public/data/waters_county_clips.json and fetched LAZILY
   * on the first county activation (0.73 MB gzip ≈ 3 s Fast 3G, ~50 ms
   * broadband). `countyClipsLoaded` flips once fetched (idempotent);
   * `countyClipsLoading` drives the county-chip spinner.
   */
  countyClipsLoaded: boolean;
  countyClipsLoading: boolean;
  /**
   * Raw slug -> countyKey->clip map, cached after the first lazy fetch. Kept
   * so a background uncontracted load that lands after the clips merge can
   * still apply clips to the freshly-loaded teal waters.
   */
  countyClipsBySlug: Record<string, Water['geometryByCounty']>;

  // Selection layer (mutually independent)
  selectedAssociationSlug: string | null; // null = no association selected
  selectedWaterSlug: string | null; // null = detail sheet closed
  /**
   * t_21d2f68d: the water detail sheet open flag, DECOUPLED from the
   * selection. Closing the sheet (Escape / × / drag) keeps `selectedWaterSlug`
   * set so the orange click focus stays on the map — the reported bug was the
   * card close (the only way to reach the filters on mobile) silently wiping
   * every highlight, which users perceived as "picking a locality clears all
   * highlights". True deselection is `selectWater(null)` (clicking another
   * water re-selects; there is no map-empty-click deselect today).
   */
  waterSheetOpen: boolean;

  // Filter layer
  countyFilter: string[]; // empty [] = all counties
  localityFilter: string[]; // empty [] = all localities (t_dd918db7)
  waterTypeFilter: WaterTypeFilter; // 'all' | 'lac' | 'rau'
  contractFilter: ContractFilter; // 'all' | 'contractate' | 'necontractate'

  // FlyTo gating (t_697ba939): one-shot flag — the association was cleared
  // as a side effect of CLICKING a water outside it, so the next
  // FlyToController pass must NOT re-fit / zoom out to the full dataset.
  suppressAssociationFlyTo: boolean;

  // F2a: association detail sheet visibility (opened from the association
  // chip on the map). Mirrors the water sheet's one-at-a-time rule: opening
  // it clears the selected water, selecting a water closes it.
  associationSheetOpen: boolean;

  // Geolocation MVP (docs/geolocation-feasibility.md): one-shot user fix +
  // the nearest contracted waters computed client-side from the loaded pool.
  // `nearbyRadiusKm` is the ADAPTIVE radius actually used (25 → 50 when too
  // few results; grows to cover the nearest-few fallback) — the map draws
  // the circle with this value and the sheet labels it.
  userPosition: { lat: number; lon: number; accuracy: number } | null;
  nearbyWaters: NearbyWater[];
  nearbyRadiusKm: number;

  // Actions
  loadData: () => Promise<void>;
  loadCountyClips: () => Promise<void>;
  selectAssociation: (slug: string | null) => void;
  selectWater: (slug: string | null) => void;
  /** Close the water detail sheet WITHOUT clearing the selection (orange focus stays). */
  closeWaterSheet: () => void;
  consumeAssociationFlyToSuppression: () => void;
  openAssociationSheet: () => void;
  closeAssociationSheet: () => void;
  toggleCounty: (county: string) => void;
  toggleLocality: (locality: string) => void;
  clearLocalities: () => void;
  setWaterTypeFilter: (type: WaterTypeFilter) => void;
  setContractFilter: (filter: ContractFilter) => void;
  /** Geolocation MVP: store a one-shot position fix + recompute nearest waters. */
  applyUserPosition: (pos: { lat: number; lon: number; accuracy: number }) => void;
  /** Geolocation MVP: clear the user marker / circle / nearby list. */
  clearUserPosition: () => void;
}

/**
 * Perf instrumentation (docs/performance-test-plan.md §9): expose a stable
 * first-paint signal for Playwright perf tests to await instead of guessing
 * with waitForTimeout. `window.__perfDataLoaded` flips true (and
 * `__perfDataLoadedAt` records `performance.now()`) the moment the map's
 * data gate opens — the MapSkeleton is replaced by the real map then.
 * No-op server-side / in old browsers.
 */
function markPerfDataLoaded() {
  if (typeof window === 'undefined') return;
  try {
    (window as unknown as { __perfDataLoaded?: boolean; __perfDataLoadedAt?: number }).__perfDataLoaded = true;
    (window as unknown as { __perfDataLoadedAt?: number }).__perfDataLoadedAt = performance.now();
  } catch {
    /* instrumentation must never break the app */
  }
}

export const useMapStore = create<MapStore>((set, get) => ({
  associations: [],
  waters: [],
  uncontracted: [],
  counties: [],
  dataUpdatedAt: null,
  dataLoaded: false,
  countyClipsLoaded: false,
  countyClipsLoading: false,
  countyClipsBySlug: {},

  selectedAssociationSlug: null,
  selectedWaterSlug: null,
  waterSheetOpen: false,

  countyFilter: [],
  localityFilter: [],
  waterTypeFilter: 'all',
  contractFilter: 'all',
  suppressAssociationFlyTo: false,
  associationSheetOpen: false,

  userPosition: null,
  nearbyWaters: [],
  nearbyRadiusKm: DEFAULT_RADIUS_KM,

  loadData: async () => {
    try {
      // P0 §4.2 / plan §4.5 (simpler alternative): ONLY the first-paint
      // files are awaited — associations + waters + counties + meta. The
      // uncontracted overlay (teal rivers/lakes) is fetched in the
      // background right after dataLoaded so the map paints immediately and
      // the teal pops in a beat later (budgets M7/M8/M9 — the uncontracted
      // 1.2 MB gzip is off the critical parse path).
      const [assocRes, watersRes, countiesRes, metaRes] = await Promise.all([
        fetch('/data/associations.json'),
        fetch('/data/waters.json'),
        fetch('/data/counties.geojson'),
        // F6: freshness meta (network-first via SW app-data tier). Optional —
        // 404 in dev (prebuild generates it only) leaves dataUpdatedAt null.
        fetch('/data/meta.json'),
      ]);
      if (!assocRes.ok || !watersRes.ok) throw new Error(`fetch failed: ${assocRes.status} / ${watersRes.status}`);
      const [associations, waters] = (await Promise.all([
        assocRes.json(),
        watersRes.json(),
      ])) as [Association[], Water[]];
      // t_6c2ac870: county polygons for the nearby-waters chip. Optional —
      // the chip falls back to the contract county when missing.
      let counties: CountyFeature[] = [];
      if (countiesRes.ok) {
        const fc = (await countiesRes.json()) as { type: string; features: CountyFeature[] };
        counties = Array.isArray(fc.features) ? fc.features : [];
      }
      // F6: optional freshness meta (offline-pwa-feasibility.md §6).
      let dataUpdatedAt: string | null = null;
      if (metaRes.ok) {
        const meta = (await metaRes.json()) as { dataUpdatedAt?: string };
        dataUpdatedAt = typeof meta.dataUpdatedAt === "string" ? meta.dataUpdatedAt : null;
      }
      set({ associations, waters, counties, dataUpdatedAt, dataLoaded: true });
      markPerfDataLoaded();
      // P0 §4.2: uncontracted overlay deferred — load in the background once
      // the map is up. t_51e028c4: ponds/lakes join the same uncontracted
      // pool (county/type/contract filters and 'Necontractat' UX apply).
      void (async () => {
        try {
          const [uncRes, uncLakesRes] = await Promise.all([
            fetch('/data/uncontracted_rivers.json'),
            fetch('/data/uncontracted_lakes.json'),
          ]);
          let extra: Water[] = [];
          if (uncRes.ok) extra = (await uncRes.json()) as Water[];
          if (uncLakesRes.ok) {
            const lakes = (await uncLakesRes.json()) as Water[];
            extra = [...extra, ...lakes];
          }
          set((s) => {
            // If the county clips already loaded, apply them to the fresh
            // teal waters too (they were empty when loadCountyClips ran).
            let pool = extra;
            const bySlug = s.countyClipsBySlug;
            if (Object.keys(bySlug).length > 0) {
              pool = extra.map((w) =>
                bySlug[w.slug] ? { ...w, geometryByCounty: bySlug[w.slug] } : w,
              );
            }
            return { ...s, uncontracted: pool };
          });
        } catch (e) {
          // Teal overlay is enhancement-only; never break the map over it.
          console.error('[map-store] background uncontracted load failed:', e);
        }
      })();
    } catch (err) {
      // Never leave the skeleton spinning forever — render an empty map instead.
      console.error('[map-store] loadData failed:', err);
      set({ dataLoaded: true });
      markPerfDataLoaded();
    }
  },

  /**
   * P0 §4.2 (plan §4.2): fetch the county render clips ONCE, lazily, on the
   * first county activation. Splits geometryByCounty out of waters.json (the
   * shipped file has none), keyed by slug. Merges each water's clips back into
   * the in-memory object so countyRenderGeometry() works unchanged. Idempotent
   * (guarded by countyClipsLoaded); countyClipsLoading drives the chip spinner.
   */
  loadCountyClips: async () => {
    const { countyClipsLoaded, countyClipsLoading } = get();
    if (countyClipsLoaded || countyClipsLoading) return;
    set({ countyClipsLoading: true });
    try {
      const res = await fetch('/data/waters_county_clips.json');
      if (!res.ok) throw new Error(`county clips fetch failed: ${res.status}`);
      const clips = (await res.json()) as Record<string, Record<string, JSON | null>>;
      set((s) => {
        const bySlug: Record<string, Water['geometryByCounty']> = {};
        const merge = (pool: Water[]) =>
          pool.map((w) => {
            const c = clips[w.slug];
            if (!c) return w;
            bySlug[w.slug] = c as Water['geometryByCounty'];
            return { ...w, geometryByCounty: bySlug[w.slug] };
          });
        return {
          ...s,
          waters: merge(s.waters),
          uncontracted: merge(s.uncontracted),
          countyClipsBySlug: bySlug,
          countyClipsLoaded: true,
          countyClipsLoading: false,
        };
      });
    } catch (err) {
      console.error('[map-store] loadCountyClips failed:', err);
      set({ countyClipsLoading: false });
    }
  },

  selectAssociation: (slug) =>
    // t_21d2f68d: selecting an association closes the water sheet but keeps
    // the water selection (orange focus) — one panel at a time, highlight stays.
    set({ selectedAssociationSlug: slug, associationSheetOpen: false, waterSheetOpen: false }),

  // F2a: the chip opens the association detail sheet; opening it dismisses
  // the water sheet (one-at-a-time, mirrors the existing selection rules).
  openAssociationSheet: () =>
    set({ associationSheetOpen: true, selectedWaterSlug: null, waterSheetOpen: false }),
  closeAssociationSheet: () => set({ associationSheetOpen: false }),
  closeWaterSheet: () => set({ waterSheetOpen: false }),

  selectWater: (slug) => {
    // t_7a7192ea Bug 2: clicking a river/lake takes over from any active
    // association filter — clear selectedAssociationSlug so the map stops
    // showing the association's green/grey coverage, then select the clicked
    // water (existing orange focus + detail card behavior takes over).
    // t_abccfd6c: EXCEPT when the clicked water BELONGS to the selected
    // association — then the association filter stays (coverage keeps
    // highlighting the association's waters) and the map does NOT re-fit /
    // zoom out (FlyToController only reacts to selectedAssociationSlug
    // changes). Only a click on a water OUTSIDE the association clears it.
    // Also drop a county/type filter that would hide the clicked water (a
    // defensive "as needed" — normally only waters that pass the filters are
    // rendered/clickable, but never leave a selection invisible).
    if (slug === null) {
      set({ selectedWaterSlug: null, waterSheetOpen: false });
      return;
    }
    const { countyFilter, localityFilter, waterTypeFilter, waters, uncontracted, selectedAssociationSlug } = get();
    const water =
      waters.find((w) => w.slug === slug) ??
      uncontracted.find((w) => w.slug === slug) ??
      null;
    // Same equality the coverage styling uses (colors.ts getFeatureStyle),
    // so a green-highlighted water keeps the association and a grey/dimmed
    // one clears it — visually consistent. Uncontracted waters have no
    // asociatie, so they always clear.
    const belongsToAssociation =
      selectedAssociationSlug !== null &&
      water !== null &&
      water.asociatie?.slug === selectedAssociationSlug;
    // t_697ba939: a click on a water OUTSIDE the association clears the
    // filter (t_7a7192ea), but that clear is a SIDE EFFECT of the click,
    // not the user leaving the association — FlyToController must NOT
    // re-fit / zoom out to the full dataset. Arm the one-shot suppression;
    // only set it when an association is actually being cleared (never
    // leave a stale flag that could swallow a later explicit clear).
    const clearingAssociationByClick = !belongsToAssociation && selectedAssociationSlug !== null;
    set({
      selectedWaterSlug: slug,
      waterSheetOpen: true,
      selectedAssociationSlug: belongsToAssociation ? selectedAssociationSlug : null,
      associationSheetOpen: false,
      suppressAssociationFlyTo: clearingAssociationByClick,
      countyFilter:
        water && countyFilter.length > 0 && !countyFilter.includes(water.judet)
          ? []
          : countyFilter,
      waterTypeFilter:
        water && waterTypeFilter !== 'all' && water.subtype !== waterTypeFilter
          ? 'all'
          : waterTypeFilter,
      localityFilter:
        water && localityFilter.length > 0 && !localityFilter.includes(water.locality ?? '')
          ? []
          : localityFilter,
    });
  },

  // t_697ba939: consumed by FlyToController — the association was cleared by
  // a water click, so the map stays put (no zoom-out to the national view).
  consumeAssociationFlyToSuppression: () => set({ suppressAssociationFlyTo: false }),

  toggleCounty: (county) => {
    const { countyFilter } = get();
    const next = countyFilter.includes(county)
      ? countyFilter.filter((c) => c !== county)
      : [...countyFilter, county];
    // P0 §4.2: the first county activation lazily fetches the split-out
    // county render clips (waters_county_clips.json). Idempotent — drives
    // the chip spinner via countyClipsLoading while it's on the wire.
    if (next.length > 0) void get().loadCountyClips();
    set({
      countyFilter: next,
      // t_dd918db7: locality is a REFINEMENT of the county selection — a
      // locality list only exists for the currently selected counties, so a
      // county change invalidates any active locality filter (plan §7.4 /
      // risk 2: same-name UATs across counties must never leak).
      localityFilter: [],
      // t_21d2f68d: do NOT dismiss the selected water — the filter may narrow
      // the map but the click focus + detail card survive (R10).
    });
  },

  toggleLocality: (locality) => {
    const { localityFilter } = get();
    const next = localityFilter.includes(locality)
      ? localityFilter.filter((l) => l !== locality)
      : [...localityFilter, locality];
    set({
      localityFilter: next,
      // t_21d2f68d: locality must NOT clear the selection — it narrows the
      // visible waters only; the click focus + detail card stay (R10). The
      // selected water is pinned into the rendered set by use-filtered-waters.
    });
  },

  clearLocalities: () => set({ localityFilter: [] }),

  setWaterTypeFilter: (type) => {
    // t_21d2f68d: same as toggleLocality — the type filter narrows the visible
    // waters but never clears the selected water.
    set({ waterTypeFilter: type });
  },

  setContractFilter: (filter) => {
    // t_21d2f68d: same as toggleLocality — the contract filter narrows the
    // visible waters but never clears the selected water.
    set({ contractFilter: filter });
  },

  // Geolocation MVP (docs/geolocation-feasibility.md §5 AC4): adaptive radius
  // — 25 km default; if fewer than 3 contracted waters are within it, expand
  // to 50 km; always show at least the nearest few regardless of radius (and
  // grow the drawn radius to cover the farthest shown entry so the circle
  // never under-states what the list claims).
  applyUserPosition: (pos) => {
    const { waters, counties } = get();
    // t_6c2ac870: attach the water's OWN county (of the segment nearest the
    // user) so the nearby card doesn't show the association's seat county
    // (e.g. 'Ilfov' for the Dâmbovița headwaters near Brașov).
    const withCounty = (nearby: NearbyWater[]): NearbyWater[] =>
      nearby.map((n) => {
        const water = waters.find((w) => w.slug === n.slug);
        return { ...n, county: water ? nearbyCounty(pos.lat, pos.lon, water, counties) : null };
      });
    let radius = DEFAULT_RADIUS_KM;
    let nearby = withCounty(nearestWaters(pos.lat, pos.lon, waters, { limit: NEARBY_LIMIT, maxKm: radius }));
    if (nearby.length < MIN_NEARBY_COUNT) {
      radius = EXPANDED_RADIUS_KM;
      nearby = withCounty(nearestWaters(pos.lat, pos.lon, waters, { limit: NEARBY_LIMIT, maxKm: radius }));
    }
    if (nearby.length < MIN_NEARBY_COUNT) {
      // Nearest-few fallback, no radius cap (e.g. deep wilderness).
      nearby = withCounty(
        waters
          .map((w) => ({ slug: w.slug, km: distanceToWaterKm(pos.lat, pos.lon, w), county: null }))
          .filter((e) => Number.isFinite(e.km))
          .sort((a, b) => a.km - b.km)
          .slice(0, NEARBY_LIMIT),
      );
      if (nearby.length > 0) {
        radius = Math.max(radius, Math.ceil(nearby[nearby.length - 1].km / 10) * 10);
      }
    }
    set({ userPosition: pos, nearbyWaters: nearby, nearbyRadiusKm: radius });
  },

  clearUserPosition: () =>
    set({ userPosition: null, nearbyWaters: [], nearbyRadiusKm: DEFAULT_RADIUS_KM }),
}));
