#!/usr/bin/env python3
"""t_45a0beae / B4 — resolve the sweep-gate DUPLICATE/PARTIAL_DUPLICATE hits.

sweep_uncontracted_overlay.py --gate exits 1 while any uncontracted overlay
entry is the same body as a contracted water (plan §5.1 pass criteria: 0
DUPLICATE + 0 PARTIAL_DUPLICATE). The baseline run found 13:

DUPLICATE (10) — the overlay body IS the contracted water; the build-time
dedupe missed it because the contracted entry carries no polygon geometry
(centroid-inside-contracted-geometry can't fire) or the names differ:
  Iaz neidentificat == Lac Pâncota / Balta Rădășeni / CCRM Ruseni /
                     CCPFB Paulian / Lac baraj pârâul Roșu / Balta Marica /
                     Acumularea Drăgășani ...
  Pârâul Morii == Râul Bloaja (Maramureș)
  Vâltori     == Râul Vîltori - Feneș (Alba)
  Tăul Păpușii == Păpuşa (Hunedoara)
Resolution: REMOVE the overlay entry — the water is already contracted.

PARTIAL_DUPLICATE (3) — a real stretch of the overlay course lies on a
contracted course (the canalized/stretch overlaps): Aranca == Canal Aranca
(Timiș), Prut == Prut – fără lacul Stânca (Botoșani), Tisza == Râul Tisa
(Maramureș). Resolution: TRIM the overlapping runs (>= 2 km, the
build-time trim threshold); remove the entry entirely when nothing
uncontracted remains.

Deterministic: reads the sweep report (data/sweep_overlay_report.json), which
is regenerated by the sweep itself before the gate decides.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

from shapely.geometry import LineString, MultiLineString, Point, shape
from shapely.strtree import STRtree

ROOT = Path(__file__).resolve().parent.parent
FE_WATERS = ROOT / "public" / "data" / "waters.json"
FE_RIVERS = ROOT / "public" / "data" / "uncontracted_rivers.json"
FE_LAKES = ROOT / "public" / "data" / "uncontracted_lakes.json"
SWEEP = ROOT / "data" / "sweep_overlay_report.json"

EPS_DEG = 0.0008
TRIM_MIN_RUN_KM = 2.0


def haversine_km(a, b):
    R = 6371.0
    dlat = math.radians(b[1] - a[1])
    dlon = math.radians(b[0] - a[0])
    la1, la2 = math.radians(a[1]), math.radians(b[1])
    h = math.sin(dlat / 2) ** 2 + math.cos(la1) * math.cos(la2) * math.sin(dlon / 2) ** 2
    return 2 * R * math.asin(math.sqrt(h))


def trim_runs(parts, contracted_mls, eps):
    """Cut stretches lying on a contracted course. A part with >= 80% of its
    points within eps of the contracted course IS part of that course (the
    canalized-bed fragments and short re-mapped segments that the sweep
    classifies PARTIAL_DUPLICATE) — dropped whole, no length floor: a 2-point
    fragment whose both endpoints sit on the canal is not a tributary mouth.
    For parts that only CROSS the contract, contiguous near-runs >= 2 km are
    cut (short confluence touches stay)."""
    out_parts = []
    for part in parts:
        if len(part) < 2:
            continue
        near = [contracted_mls.distance(Point(lon, lat)) <= eps for lon, lat in part]
        frac = sum(near) / len(near)
        if frac >= 0.8:
            continue  # this part IS the contracted stretch
        # run-level trim for longer partial overlaps not caught by the
        # whole-part test (e.g. a course that crosses the contract mid-way)
        n = len(part)
        kept: list = []
        cur: list = []
        i = 0
        while i < n:
            if near[i]:
                j = i
                while j < n and near[j]:
                    j += 1
                run_len = sum(haversine_km(part[k], part[k - 1]) for k in range(i + 1, j))
                if run_len < TRIM_MIN_RUN_KM:
                    cur.extend(part[i:j])
                else:
                    if len(cur) >= 2:
                        kept.append(cur)
                    cur = []
                i = j
            else:
                cur.append(part[i])
                i += 1
        if len(cur) >= 2:
            kept.append(cur)
        out_parts.extend(p for p in kept if len(p) >= 2)
    if not out_parts:
        return None
    if len(out_parts) == 1:
        return {"type": "LineString", "coordinates": out_parts[0]}
    return {"type": "MultiLineString", "coordinates": out_parts}


def main() -> None:
    report = json.loads(SWEEP.read_text(encoding="utf-8"))
    blockers = [h for h in report if h["label"] in ("DUPLICATE", "PARTIAL_DUPLICATE")]
    if not blockers:
        print("[b4] no sweep-gate blockers — nothing to fix")
        return
    print(f"[b4] {len(blockers)} blockers from {SWEEP.name}")

    waters = json.loads(FE_WATERS.read_text(encoding="utf-8"))
    rivers = json.loads(FE_RIVERS.read_text(encoding="utf-8"))
    lakes = json.loads(FE_LAKES.read_text(encoding="utf-8"))

    # contracted course index: slug -> MultiLineString
    contracted_courses = []
    for w in waters:
        g = w.get("geometry")
        if not g or g.get("type") not in ("LineString", "MultiLineString"):
            continue
        parts = g["coordinates"] if g["type"] == "MultiLineString" else [g["coordinates"]]
        try:
            mls = MultiLineString(parts)
        except Exception:
            continue
        contracted_courses.append((w["slug"], mls))
    by_slug = {c[0]: c[1] for c in contracted_courses}

    removed_r = removed_l = 0
    trimmed_r = 0
    for h in blockers:
        kind = h["kind"]
        entries = rivers if kind == "river" else lakes
        target = next((e for e in entries if e["slug"] == h["unc_slug"]), None)
        if target is None:
            print(f"  WARN {h['unc_slug']} already gone — skip")
            continue
        wslug = h["water_slug"]
        if h["label"] == "DUPLICATE":
            entries.remove(target)
            if kind == "river":
                removed_r += 1
            else:
                removed_l += 1
            print(f"  REMOVE {kind:6} {h['unc_name'][:38]:40} == {h['water_name'][:38]} "
                  f"({h['water_judet']})")
            continue
        # PARTIAL_DUPLICATE: trim the contracted stretch
        mls = by_slug.get(wslug)
        if mls is None:
            # contracted water's course not found by slug — fall back to any
            # contracted course near the overlay (search by name match)
            cand = next((m for s, m in contracted_courses if s == wslug), None)
            if cand is None:
                print(f"  WARN {h['unc_name']}: contracted course {wslug} missing — skip trim")
                continue
            mls = cand
        g = target["geometry"]
        parts = g["coordinates"] if g["type"] == "MultiLineString" else [g["coordinates"]]
        new_geom = trim_runs(parts, mls, EPS_DEG)
        if new_geom is None:
            entries.remove(target)
            print(f"  REMOVE {kind:6} {h['unc_name'][:38]:40} (fully contracted after trim)")
            if kind == "river":
                removed_r += 1
        else:
            target["geometry"] = new_geom
            coords = new_geom["coordinates"] if new_geom["type"] == "LineString" else [
                p for part in new_geom["coordinates"] for p in part
            ]
            target["lengthKm"] = round(sum(haversine_km(coords[i - 1], coords[i])
                                           for i in range(1, len(coords))), 1)
            bbox = [round(min(p[0] for p in coords), 5), round(min(p[1] for p in coords), 5),
                    round(max(p[0] for p in coords), 5), round(max(p[1] for p in coords), 5)]
            target["bbox"] = bbox
            target["coordinates"] = [round((bbox[0] + bbox[2]) / 2, 5),
                                     round((bbox[1] + bbox[3]) / 2, 5)]
            trimmed_r += 1
            print(f"  TRIM   {kind:6} {h['unc_name'][:38]:40} (cut contracted stretch of "
                  f"{h['water_name'][:30]}; now {target['lengthKm']} km)")

    FE_RIVERS.write_text(json.dumps(rivers, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")
    FE_LAKES.write_text(json.dumps(lakes, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")
    print(f"[b4] rivers: removed {removed_r}, trimmed {trimmed_r} → {len(rivers)}")
    print(f"[b4] lakes: removed {removed_l} → {len(lakes)}")


if __name__ == "__main__":
    main()